#!/usr/bin/env python3
"""Generate every printed numeral from saved raw results/metadata. Stdlib; MIT."""
from pathlib import Path
import json,math,csv,statistics
P=Path(__file__).resolve().parents[1];R=P/'results';T=P/'paper';T.mkdir(exist_ok=True)
def load(n):return json.loads((R/n).read_text())
c=load('census_1e9.json');big=load('base15_1e10.json');rec=load('reconstruction.json');exc=load('exclusions.json');naive=load('naive_1e6.json');meta=load('editorial_metadata.json')
def delta(v):return v[3]/sum(v[2:])-v[1]/sum(v[:2])
def num(x):return f'{x:,}'.replace(',',r'\,')
def fmt(x):return f'{x:+.6f}'
def disc(a):return a if a%4==1 else 4*a
mac=[]
def define(k,v):mac.append('\\newcommand{\\'+k+'}{'+str(v)+'}')
for k,v in meta['constants'].items():define(k,v)
for k,v in meta.get('ai_models',{}).items():define(k,v)
for k,v in {'AuthorName':meta['author'],'Affiliation':meta['affiliation'],'AuthorOrcid':meta['orcid'],'TextLicense':meta['text_license'],'CodeLicense':meta['code_license']}.items():define(k,v)
bases=list(map(int,c['bases']));sel=[x['a'] for x in rec['bases']];positive=[a for a in bases if delta(c['bases'][str(a)])>0]
mat={tuple(map(int,k.split(','))):delta(v) for k,v in c['matrix'].items()};off=[v for (a,b),v in mat.items() if a!=b];asym={(a,b):abs(mat[a,b]-mat[b,a]) for a in sel for b in sel if a<b};ab=max(asym,key=asym.get)
values={'CensusBound':num(c['limit']),'LargeBound':num(big['limit']),'SmallBound':num(naive['bound']),'PairCount':num(c['n_pairs']),'LargePairCount':num(big['n_pairs']),'BaseCount':len(bases),'SelectedCount':len(sel),'PositiveCount':len(positive),'NegativeCount':len(bases)-len(positive),'BaseMaximum':max(bases),'LowerPrime':c['lower'],'PositiveBases':','.join(map(str,positive)),'SelectedBases':','.join(map(str,sel)),'BaseFifteenDelta':fmt(delta(c['bases']['15'])),'BaseFifteenLargeDelta':fmt(delta(big['bases']['15'])),'RatioMinimum':f"{min(x['ratio'] for x in rec['bases']):.3f}",'RatioMaximum':f"{max(x['ratio'] for x in rec['bases']):.3f}",'RatioDigits':3,'OffDiagonalCount':len(off),'NegativeOffDiagonal':sum(x<0 for x in off),'OffMean':fmt(statistics.mean(off)),'AsymMean':f'{statistics.mean(asym.values()):.6f}','AsymMax':f'{asym[ab]:.6f}','AsymPair':','.join(map(str,ab)),'DiagonalHits':exc['diagonal_hits'],'LawCount':num(c['mixed_law'][0]),'LawViolations':sum(c['mixed_law'][1:]),'NaivePairs':num(naive['pairs']),'NaiveEligible':num(naive['eligible']),'NaiveViolations':naive['violations26']+naive['violations62'],'EulerCutoff':num(rec['cutoff']),'EulerBound':f"{rec['tail_relative_bound']:.7f}",'ArtinLower':f"{float(rec['Artin_lower']):.9f}",'ArtinUpper':f"{float(rec['Artin_upper']):.9f}",'MaxGap':c['max_gap'],'MainRuntime':f"{c['seconds']:.2f}",'LargeRuntime':f"{big['seconds']:.2f}",'NaiveRuntime':f"{naive['seconds']:.2f}",'PositiveMinConductor':min(map(disc,positive)),'PairStartOld':5,'DensityPrecision':rec['decimal_precision'],'ValidationBound':1000,'ValidationBlocks':'2,17,31,1000','Threads':28,'ChannelSlots':150,'GapCapacity':300,'EndpointPair':'5,7','FreshExceptionPair':'7,11','OldCutoff':num(100000)}
for k,v in values.items():define(k,v)
(T/'numbers.tex').write_text('% Generated by code/make_tables.py; do not edit.\n'+'\n'.join(mac)+'\n')
# Full integer evidence rather than rounded deltas alone.
s=[r'\begin{longtable}{r r r r r r r}',r'\caption{Squarefree-base census. All consecutive pairs have $\LowerPrime\le p<q<\CensusBound$. Counts use the order $(X,Y)$; $D_a$ is the quadratic conductor.}\label{tab:census}\\',r'\toprule $a$ & $D_a$ & $n_{\Zero\Zero}$ & $n_{\Zero\One}$ & $n_{\One\Zero}$ & $n_{\One\One}$ & $\delta_a$\\\midrule\endfirsthead',r'\toprule $a$ & $D_a$ & $n_{\Zero\Zero}$ & $n_{\Zero\One}$ & $n_{\One\Zero}$ & $n_{\One\One}$ & $\delta_a$\\\midrule\endhead',r'\midrule\multicolumn{7}{r}{Continued on next page}\\\endfoot',r'\bottomrule\endlastfoot']
for a in bases:
 v=c['bases'][str(a)];s.append(' & '.join([str(a),str(disc(a))]+[num(x) for x in v]+[fmt(delta(v))])+r'\\')
s.append(r'\end{longtable}');(T/'census_table.tex').write_text('\n'.join(s)+'\n')
s=[r'\begin{tabular}{rrrrr}',r'\toprule $a$ & $M_a$ & $\delta_{\rm emp}$ & $\delta_{\rm rec}$ & Ratio\\\midrule']
for x in rec['bases']:s.append(f"{x['a']} & {num(x['M'])} & {fmt(x['delta_emp'])} & {fmt(x['delta_rec'])} & {x['ratio']:.4f}"+r'\\')
s.extend([r'\bottomrule',r'\end{tabular}']);(T/'reconstruction_table.tex').write_text('\n'.join(s)+'\n')
for part,cols in enumerate((sel[:6],sel[6:]),1):
 s=[r'\begin{tabular}{r'+'r'*len(cols)+'}',r'\toprule $a\backslash b$ & '+' & '.join(map(str,cols))+r'\\\midrule']
 for a in sel:s.append(str(a)+' & '+' & '.join(fmt(mat[a,b]) for b in cols)+r'\\')
 s.extend([r'\bottomrule',r'\end{tabular}']);(T/f'matrix_{part}.tex').write_text('\n'.join(s)+'\n')
s=[r'\begin{tabular}{rrl}',r'\toprule Base & Modulus & Nonvacuous excluded even classes\\\midrule']
for x in exc['pairs']:
 if x['a']==x['b']:
  s.append(f"{x['a']} & {x['modulus']} & "+(','.join(map(str,x['gaps'])) if x['gaps'] else r'\text{none}')+r'\\')
s.extend([r'\bottomrule',r'\end{tabular}']);(T/'exclusion_table.tex').write_text('\n'.join(s)+'\n')
s=[r'\begin{tabular}{rrrl}',r'\toprule $g$ & $r$ & $r+g\pmod{\TwentyFour}$ & Successor condition\\\midrule']
for g,rows in exc['proof'].items():
 for x in rows:s.append(f"{g} & {x['r']} & {x['s']} & "+(r'$\chi_{\Six}=+\One$' if x['unit'] else r'not a reduced residue')+r'\\')
s.extend([r'\bottomrule',r'\end{tabular}']);(T/'proof_table.tex').write_text('\n'.join(s)+'\n')
# Bibliographic numerals and identifier digits also generated, not handwritten.
def tex(s):return s.replace('für',r'f\"ur').replace('Tinková',r'Tinkov\'{a}')
s=[r'\begin{thebibliography}{99}']
for b in meta['references']:
 line=r'\bibitem{'+b['key']+'} '+tex(b['authors'])+'. '+tex(b['title'])+'. '+tex(b['journal'])
 if 'volume' in b:line+=' '+b['volume']+' ('+b['year']+'), '+b['pages']
 line+='.'
 if 'doi' in b:line+=r' \url{https://doi.org/'+b['doi']+'}.'
 if 'url' in b:line+=r' \url{'+b['url']+'}.'
 s.append(line)
s.append(r'\end{thebibliography}');(T/'references.tex').write_text('\n'.join(s)+'\n')
# Machine-readable summary used by final audit.
(R/'generated_summary.json').write_text(json.dumps(values,indent=2)+'\n')
print('Generated numbers.tex, census, reconstruction, split matrix, exclusion/proof tables and references.tex')
